### ISSUE TITLE
error when run airflow with daemon

### ISSUE THREAD

**Issue by liuxun666** [V0RT3X4/airflow-deploy-plugin#2]
when run airflow with -D option. /deployment/status got the following error.
> git.exc.GitCommandError: Cmd('git') failed due to: exit code(-13) cmdline: git fetch --prune -v origin

**Comment by kujon** [comment]
Hi, @liuxun666 👋 Thanks for spotting the issue. Does the error not occur if you try to run Airflow in the foreground? Additionally, would you mind trying executing `git fetch --prune -v origin` manually on the machine running your airflow deamon to determine whether your dags repo is configured correctly, please?
